#!/bin/bash
#a script for the automation of the master portion of the laplace daily check

ssh master1 "echo 'hostname is:'; hostname ;
 echo 'Check IPMI:' ; ipmitool -c sel elist ;
 echo 'uptime is:'; uptime ;
 echo 'Memory and Swap usage are:'; free -hm ;
 echo 'Check dirvish backups:'; /var/spool/nagios/get_dirvish_results.sh ;
 echo 'disk space in opt:'; df -h /opt ;
 echo 'disk space available:'; df -h ;
 echo 'RAID status:'; /opt/MegaRAID/MegaCli/MegaCli64 -ldinfo -lall -aall ; " 
